version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitnesstracker_web
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Conexiunea catre containerul de SQL Server
      - ConnectionStrings__DefaultConnection=Server=db;Database=FitnessTrackerDB;User=sa;Password=ParolaSuperSigura123!;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fitnesstracker_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ParolaSuperSigura123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: